# Site settings
title: The Digital Innovation Group @ ASU
#email: doru.mihai@haufe-lexware.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Haufe-Lexware
github_username:  Haufe-Lexware

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"

plugins: 
  - jekyll-paginate
  - jekyll-get-json

# Google Analytics
google_analytics: UA-44225403-5
